id: A464F28F2
title: 'CV_Chapter XXII: Tathāgataparīkṣā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:09:25.101049
  last_modified_at: 2022-03-01 23:09:25.101052
