id: A464F28F2
title: 'CVI_Chapter XXVI: Dvādaśāṅgaparīkṣā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:09:25.076866
  last_modified_at: 2022-03-01 23:09:25.076869
