id: A464F28F2
title: 'CIV_Chapter XVII: Karmaphalaparīkṣā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:09:25.015752
  last_modified_at: 2022-03-01 23:09:25.015759
