id: A464F28F2
title: 'CVI_Chapter XXVII: Dr̥ṣṭiparīkṣā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:09:25.086199
  last_modified_at: 2022-03-01 23:09:25.086202
