id: A464F28F2
title: 'CIV_Chapter XX: Sāmagrīparīkṣā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:09:25.030906
  last_modified_at: 2022-03-01 23:09:25.030909
