id: A464F28F2
title: 'CIV_Chapter XIX: Kālaparīkṣā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:09:24.960852
  last_modified_at: 2022-03-01 23:09:24.960856
