id: A464F28F2
title: 'CIII_Chapter XV: Svabhāvaparīkṣā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:09:24.909956
  last_modified_at: 2022-03-01 23:09:24.909962
