id: A464F28F2
title: 'CIII_Chapter XII: Duḥkhaparīkṣā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:09:24.892684
  last_modified_at: 2022-03-01 23:09:24.892690
